######################################################################
#
# File name : tb_pll_compile.do
# Created on: Fri Jan 03 18:10:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\my_app\\modelsim_2020\\win64\\vlib modelsim_lib/work
D:\\my_app\\modelsim_2020\\win64\\vlib modelsim_lib/msim

D:\\my_app\\modelsim_2020\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\my_app\\modelsim_2020\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\my_app\\modelsim_2020\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../pll.gen/sources_1/ip/clk_wiz_0" \
"../../../../pll.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../pll.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/pll.v" \
"../../../../../sim/tb/tb_pll.v" \


# compile glbl module
D:\\my_app\\modelsim_2020\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

