######################################################################
#
# File name : tb_pll_wave.do
# Created on: Fri Jan 03 18:10:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
