######################################################################
#
# File name : tb_pll_simulate.do
# Created on: Fri Jan 03 18:10:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_pll xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_pll_wave.do}

view wave
view structure
view signals

do {tb_pll.udo}

run 1000ns
