#时序约束
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

#IO引脚约束
#------------------------------系统时钟和复位-----------------------------------
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

#-----------------------------------LED-----------------------------------------
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports led]

#------------------------------------SPI-------------------------------------------
#SPI 相关设置
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property MARK_DEBUG true [get_nets sys_rst_n_IBUF]
set_property MARK_DEBUG true [get_nets led_OBUF]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[0]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[3]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[5]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[7]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[1]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[2]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[4]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[6]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[8]}]
set_property MARK_DEBUG true [get_nets {cnt_2ms_reg[9]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[0]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[2]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[5]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[6]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[7]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[8]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[1]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[3]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[4]}]
set_property MARK_DEBUG true [get_nets {cnt_2s_reg[9]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[0]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[1]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[2]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[3]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[4]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[5]}]
set_property MARK_DEBUG true [get_nets {cnt_2us_reg[6]}]
set_property MARK_DEBUG true [get_nets direction]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cnt_2s_reg[0]} {cnt_2s_reg[1]} {cnt_2s_reg[2]} {cnt_2s_reg[3]} {cnt_2s_reg[4]} {cnt_2s_reg[5]} {cnt_2s_reg[6]} {cnt_2s_reg[7]} {cnt_2s_reg[8]} {cnt_2s_reg[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {cnt_2ms_reg[0]} {cnt_2ms_reg[1]} {cnt_2ms_reg[2]} {cnt_2ms_reg[3]} {cnt_2ms_reg[4]} {cnt_2ms_reg[5]} {cnt_2ms_reg[6]} {cnt_2ms_reg[7]} {cnt_2ms_reg[8]} {cnt_2ms_reg[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {cnt_2us_reg[0]} {cnt_2us_reg[1]} {cnt_2us_reg[2]} {cnt_2us_reg[3]} {cnt_2us_reg[4]} {cnt_2us_reg[5]} {cnt_2us_reg[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list direction]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list led_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list sys_rst_n_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF_BUFG]
